/*
 * Renders the settings page's text-size preview with the firmware's own Gothic
 * glyphs, so the sample is pixel-for-pixel what the watch draws. The phone has
 * no copy of that font, and approximating it with the phone's sans came out
 * half again too wide.
 *
 * Run after changing SAMPLE or the offered sizes:
 *   node tools/gothic-preview.mjs [path to a pebbleos checkout]
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { crc32, deflateSync } from "node:zlib";
import wrap from "../src/embeddedjs/wrap.js";

const PEBBLEOS = process.argv[2] || process.env.PEBBLEOS || "../pebbleos";
const SIZES = [14, 18, 24, 28, 36];
const SAMPLE =
  "Roughly what a reply looks like on the watch at this size, on the real " +
  "screen of 200 by 228 pixels.";

// The emery screen and the padding main.js draws with.
const WIDTH = 200;
const HEIGHT = 228;
const PADDING = 6;

function readFont(size) {
  const name = "GOTHIC_" + String(size).padStart(2, "0") + ".pbf";
  const path = ["resources/common/base/pbf", "resources/normal/base/pbf"]
    .map((dir) => `${PEBBLEOS}/${dir}/${name}`)
    .find(existsSync);
  if (!path) {
    throw new Error(`${name} not found under ${PEBBLEOS} — pass the checkout as an argument`);
  }

  const buf = readFileSync(path);
  // Every shipped Gothic is a v3 header with 16-bit offsets. Refusing anything
  // else beats parsing it wrong and writing a PNG full of noise.
  if ((buf[0] & 0x3f) !== 3 || !(buf[9] & 1)) {
    throw new Error(`${name}: unexpected font format`);
  }

  const glyphs = buf.readUInt16LE(2);
  const codepointBytes = buf[7];
  const entry = codepointBytes + 2;
  const tableAt = 10 + 4 * buf[6];
  const dataAt = tableAt + entry * glyphs;

  const table = new Map();
  for (let i = 0; i < glyphs; i++) {
    const at = tableAt + entry * i;
    const codepoint = codepointBytes === 2 ? buf.readUInt16LE(at) : buf.readUInt32LE(at);
    table.set(codepoint, dataAt + buf.readUInt16LE(at + codepointBytes));
  }

  return { buf, lineHeight: buf[1] + 2, table };
}

function glyph(font, character) {
  const at = font.table.get(character.codePointAt(0));
  if (at === undefined) {
    return null;
  }
  const { buf } = font;
  return {
    width: buf[at],
    height: buf[at + 1],
    left: buf.readInt8(at + 2),
    top: buf.readInt8(at + 3),
    advance: buf.readInt8(at + 4),
    bits: buf.subarray(at + 5),
  };
}

function draw(font) {
  const pixels = new Uint8Array(WIDTH * HEIGHT).fill(1);
  const spans = wrap(SAMPLE, WIDTH - 2 * PADDING, (text) =>
    [...text].reduce((sum, c) => sum + (glyph(font, c)?.advance ?? 0), 0)
  );

  for (let index = 0; index < spans.length / 2; index++) {
    const line = SAMPLE.slice(spans[2 * index], spans[2 * index + 1]);
    const top = PADDING + index * font.lineHeight;
    let x = PADDING;
    for (const character of line) {
      const g = glyph(font, character);
      if (!g) {
        continue;
      }
      for (let row = 0; row < g.height; row++) {
        for (let column = 0; column < g.width; column++) {
          const bit = row * g.width + column;
          if (!((g.bits[bit >> 3] >> (bit & 7)) & 1)) {
            continue;
          }
          const px = x + g.left + column;
          const py = top + g.top + row;
          if (px >= 0 && px < WIDTH && py >= 0 && py < HEIGHT) {
            pixels[py * WIDTH + px] = 0;
          }
        }
      }
      x += g.advance;
    }
  }

  return pixels;
}

function png(pixels) {
  const rowBytes = Math.ceil(WIDTH / 8);
  const raw = Buffer.alloc((rowBytes + 1) * HEIGHT);
  for (let y = 0; y < HEIGHT; y++) {
    const row = y * (rowBytes + 1) + 1;
    for (let x = 0; x < WIDTH; x++) {
      if (pixels[y * WIDTH + x]) {
        raw[row + (x >> 3)] |= 0x80 >> (x & 7);
      }
    }
  }

  const chunk = (type, body) => {
    const out = Buffer.alloc(body.length + 12);
    out.writeUInt32BE(body.length, 0);
    out.write(type, 4, "ascii");
    body.copy(out, 8);
    out.writeUInt32BE(crc32(out.subarray(4, 8 + body.length)), 8 + body.length);
    return out;
  };

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(WIDTH, 0);
  ihdr.writeUInt32BE(HEIGHT, 4);
  ihdr[8] = 1; // one bit per pixel
  ihdr[9] = 0; // greyscale

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", ihdr),
    chunk("IDAT", deflateSync(raw, { level: 9 })),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

const previews = {};
for (const size of SIZES) {
  const font = readFont(size);
  const image = png(draw(font));
  previews[size] = "data:image/png;base64," + image.toString("base64");
  console.log(`GOTHIC_${size}: ${image.length} bytes`);
}

writeFileSync(
  new URL("../src/pkjs/preview.js", import.meta.url),
  "/* Generated by tools/gothic-preview.mjs — the sample drawn with the real\n" +
    "   Gothic glyphs, at the watch's own 200x228. Do not edit by hand. */\n" +
    "module.exports = " +
    JSON.stringify(previews, null, 2) +
    ";\n"
);
console.log("wrote src/pkjs/preview.js");
